### ISSUE TITLE
DONE Debian/Ubuntu/Mint packaging

### ISSUE THREAD

**Issue by farhi** [rom1v/rsshfs#5]
Hello,

We, the Data Reduction and Analysis Group at Synchrotron SOLEIL, have pushed `rsshfs` into Debian/Ubuntu/Mint.

It is currently available at:
- https://tracker.debian.org/pkg/rsshfs
- https://packages.debian.org/unstable/rsshfs

It should be available in the future Debian-class systems and installable with `apt install rsshfs`.

Cheers, Emmanuel.

**Comment by rom1v** [comment]
Oh, great, thank you!

So the tool still works 10 years later, I guess? :tada:

**Comment by farhi** [comment]
Oh yes it does, and is very handy, especially when systems get increasingly enclosed, preventing data exchange.

Merci pour votre script, simple et efficace.

**Comment by Benjamin-Loison** [comment]
Has Ubuntu/Linux Mint availability been ever checked?

On ARM 64 Oracle Ubuntu 24 VPS I face:

```bash
sudo apt install -y rsshfs
```
<details>
<summary>Output:</summary>

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package rsshfs
```
</details>

after `apt update`.

Personal notes: [Benjamin_Loison/rsshfs/issues/6](https://codeberg.org/Benjamin_Loison/rsshfs/issues/6)

**Comment by farhi** [comment]
Hello, 

the `rsshfs` debian package was pushed to debian on Sept 2024. 
- https://tracker.debian.org/pkg/rsshfs

Your Ubuntu release LTS 24.04, based on debian/unstable, does not have this package indeed. You need to upgrade to e.g. 25.10 or 26.04, or Debian Trixie.
